2주차 연습문제 코드리뷰 부탁드립니다!
utilForever/2024-HSPACE-Rust-LinuxKernel pull request #1
Opened 2024-07-27 08:38 UTC by gudtldn

2024-07-28 15:15 UTC, utilForever requested changes
수고하셨습니다. 보시고 궁금한 거 있으면 추가로 질문 남겨주세요.

2024-07-28 15:15 UTC, utilForever commented on 3 - Assignment/240714 - Rust Basic + Linux Kernel, Week 2, Day 2/collatz-sequence/src/lib.rs
> +    while n != 1 {
틀린 건 아니지만 다음 코드가 좀 더 명확해 보입니다.
```suggestion
    while n > 1 {
```

2024-07-28 15:15 UTC, utilForever commented on 3 - Assignment/240714 - Rust Basic + Linux Kernel, Week 2, Day 2/collatz-sequence/src/lib.rs
> +        }
이렇게 축약형으로 쓸 수도 있습니다.
```suggestion
        n = if n % 2 == 0 { n / 2 } else { 3 * n + 1 };
```

2024-07-28 15:15 UTC, utilForever commented on 3 - Assignment/240714 - Rust Basic + Linux Kernel, Week 2, Day 2/nested-arrays/src/lib.rs
> +    ]
틀린 건 아니지만, 이후에 배열의 크기가 변했을 때는 코드를 다시 작성해야 하는 문제가 있습니다.
유지 보수를 위해서 다음과 같이 작성하는 게 좀 더 좋겠네요.
```suggestion
    let mut ret = [[0; 3]; 3];

    for i in 0..3 {
        for j in 0..3 {
            ret[i][j] = matrix[j][i];
        }
    }

    ret
```

2024-07-28 15:15 UTC, utilForever commented on 3 - Assignment/240714 - Rust Basic + Linux Kernel, Week 2, Day 2/role-playing-game/src/lib.rs
> +                mana: if self.mana.is_some() { Some(100) } else { None },
이 코드가 맞나요? 지문을 보면 마나는 플레이어 레벨이 10 이상일 때만 가질 수 있습니다.

2024-07-28 15:15 UTC, utilForever commented on 3 - Assignment/240714 - Rust Basic + Linux Kernel, Week 2, Day 2/role-playing-game/src/lib.rs
> +            Some(mana) => {
오늘 배운 패턴 매칭에서의 `ref mut`을 사용하는 방법도 있겠습니다.

2024-07-28 15:15 UTC, utilForever commented on 3 - Assignment/240714 - Rust Basic + Linux Kernel, Week 2, Day 2/rpn-calculator/src/lib.rs
> +        }
오늘 배웠던 패턴 매칭을 이용해서 다시 짜보는 건 어떨까요?

2024-07-28 15:15 UTC, utilForever commented on 3 - Assignment/240714 - Rust Basic + Linux Kernel, Week 2, Day 2/minesweeper/src/lib.rs
> +            }
음수만 체크하면 되는 걸까요?

2024-07-28 15:15 UTC, utilForever commented on 3 - Assignment/240714 - Rust Basic + Linux Kernel, Week 2, Day 2/minesweeper/src/lib.rs
> +fn get_mine_count(minefield: &[&str], x: usize, y: usize) -> String {
리턴 타입이 `String`일 필요가 있을까요?

2024-07-28 15:15 UTC, utilForever commented on 3 - Assignment/240714 - Rust Basic + Linux Kernel, Week 2, Day 2/minesweeper/src/lib.rs
> +        for j in -1..=1 {
범위를 좀 더 아름답게 표현하는 방법이 없을까요? `saturating_sub` 등을 사용해서 말이죠.

2024-07-28 15:15 UTC, closed without merging

2024-07-29 09:11 UTC, gudtldn commented on 3 - Assignment/240714 - Rust Basic + Linux Kernel, Week 2, Day 2/role-playing-game/src/lib.rs
> +                mana: if self.mana.is_some() { Some(100) } else { None },
어차피 레벨이 10이상일때만 `mana`가 Some이니까 `self.mana.is_some()`으로 해결하였습니다.